services:
  db:
    image: postgres:15
    container_name: tasks_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: tasks_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    command: sh -c "alembic upgrade head && uvicorn tasks.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
    - .env
    working_dir: /usr/src
    volumes:
      - ./src:/usr/src
      - ./src/tasks/logs:/usr/src/tasks/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
