line-length = 79
target-version = "py312"
extend-exclude = ["src/migrations"]

[lint]
select = ["E", "F", "I", "B"]
ignore = ["E501", "B904"]

[lint.per-file-ignores]
"src/tasks/db/models/*.py" = ["F821"]
"src/tasks/api/endpoints/*.py" = ["B008"]
"src/tasks/api/deps.py" = ["B008"]