from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "6fa6f4e20f9e"
down_revision: Union[str, Sequence[str], None] = "b85f64aef513"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "last_deadline_notice_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "last_deadline_notice_at")
    # ### end Alembic commands ###
