from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75c15102f0a5'
down_revision: Union[str, Sequence[str], None] = '6fa6f4e20f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'teacher_id')
    # ### end Alembic commands ###
