name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            src/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r src/requirements.txt
          pip install ruff pytest-cov

      - name: Ruff
        run: |
          ruff version
          ruff check .

      - name: Pytest
        env:
          PYTHONPATH: src
        run: |
          pytest -q --cov=tasks --cov-report=xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
